services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 30s
    depends_on:
      minio-client:
        condition: service_healthy
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    volumes:
      - minio-data:/data1
    ports:
      - 8011:9001
      - 8012:9099
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    # Go to minio console via 127.1.1.1:8012
    command: server --console-address :9099 --address :9001 /minio-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 60

  minio-client:
    image: minio/mc:RELEASE.2024-11-17T19-35-25Z
    volumes:
      - "./data/sample.csv:/sample.csv"
    stdin_open: true
    tty: true
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9001 minio minio123;
      /usr/bin/mc mb minio/test --ignore-existing;
      /usr/bin/mc cp sample.csv minio/test/sample.csv;
      /usr/bin/mc cp sample.csv minio/test/sample/date=2025-10-12/sample.csv;
      touch /tmp/ready;
      /bin/bash;
      "
    depends_on:
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ls", "/tmp/ready"]
      interval: 5s
      timeout: 2s
      retries: 60

volumes:
  minio-data:
